config/routes.rb
Rails.application.routes.draw do
  get 'carts/new'
  get 'carts/show'
  get 'carts/create'
  devise_for :users
  resources :products
  resources :categories
  resources :orders
  resource :cart
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  post 'carts/add_product/:id', to: 'carts#add_product', as: 'add_product'
  post 'carts/remove_product/:id', to: 'carts#remove_product', as: 'remove_product'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
  get '/delete_session_cart', to: 'products#delete_session_cart', via: [:destroy]
  get '/empty_cart', to: 'carts#empty_cart', via: [:destroy]
  delete 'products/destroy_for_session/:id', to: 'products#destroy_for_session', as: 'destroy_for_session'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'products#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :products
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_and_belongs_to_many :products
  belongs_to :user, optional: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :first_name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :last_name, presence: true, length: { minimum: 1, maximum: 30 }
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  enum :status, {
    'Out of stock': 'out_of_stock',
    'In stock': 'in_stock',
    'Running low': 'running_low'
  }, default: 'in_stock'
  belongs_to :category, optional: true
  has_and_belongs_to_many :order
  has_and_belongs_to_many :carts
  validates :title, :description, :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1 }
  after_initialize :set_default_role, if: :new_record?
  has_one :cart
  has_many :orders
  validates :first_name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :last_name, presence: true, length: { minimum: 1, maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { minimum: 3, maximum: 40 }

  accepts_nested_attributes_for :orders
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_cart_products

  def set_cart_products
    if user_signed_in?
      @cart = current_user.cart || current_user.create_cart
      session[:cart] = nil unless @cart.products.empty?
      @cart.product_ids = session[:cart] unless session[:cart].nil?
      @cart
    else
      session[:cart] ||= []
      @cart = Product.find(session[:cart])
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email role first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email role first_name last_name])
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def add_product
    ids = @cart.product_ids << params[:id].to_i
    @cart.update(product_ids: ids)
    redirect_to root_path
  end

  def remove_product
    ids = @cart.product_ids
    ids.delete(params[:id].to_i)
    @cart.update(product_ids: ids)
    redirect_to root_path
  end

  def empty_cart
    @cart.update(product_ids: nil)
    redirect_to root_path
  end

  def show; end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = collection
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = resource
  end

  def update
    @category = resource
    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = resource
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted.'
  end

  private

  def collection
    Category.all
  end

  def resource
    collection.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(orders_params)

    if @order.save
      session[:cart] = nil
      @cart.update(product_ids: nil) unless current_user.nil?
      redirect_to root_path, notice: 'Order was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def orders_params
    params.permit(:first_name, :last_name, :phone, :address, :user_id, product_ids: [])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to root_path
  end

  def delete_session_cart
    session[:cart] = nil
    redirect_to root_path, notice: 'Cart was successfully deleted.'
  end

  def index
    @products = collection
  end

  def show
    @product = resource
  end

  def new
    @product = Product.new
  end

  def edit
    @product = resource
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @product = resource
    if @product.update(product_params)
      redirect_to products_url, notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product = resource
    if @product.carts.empty?
      @product.destroy
      flash[:notice] = 'Product was successfully destroyed.'
    else
      flash[:notice] = 'The product cannot be removed, it is in the shopping cart.'
    end
    redirect_to root_path
  end

  def destroy_for_session
    @product = resource
    if session[:cart].exclude?(@product.id)
      @product.destroy
      flash[:notice] = 'Product was successfully destroyed.'
    else
      flash[:notice] = 'The product cannot be removed, it is in the shopping cart.'
    end
    redirect_to root_path
  end

  private

  def collection
    Product.all
  end

  def resource
    collection.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id, :status, :order_id, :cart_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def hello(name)
    "Hello #{name}"
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def total_price_session
    price = Product.find(session[:cart]).collect(&:price).sum
  end

  def total_price_current_user
    price = Product.find(current_user.cart.product_ids).collect(&:price).sum
  end
end

app/views/categories/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to products", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex items-center justify-between">
    <h1 class="text-4xl font-bold text-blue-600">Categories</h1>
    <%= link_to 'New category', new_category_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded mt-2" %>
  </div>
  <div class="container flex flex-row flex-wrap justify-around">
    <% @categories.each do |category| %>
      <div class="p-6 my-4 bg-white border-2 border-gray-200 rounded-md shadow-sm hover:shadow-lg">
        <p class="my-5">
          <strong class="block mb-1 font-medium text-blue-600">Name:</strong>
          <%= category.name %>
        </p>
        <div class="flex items-center gap-2 p-2 my-2">
          <% if action_name != "show" %>
            <%= link_to 'Edit this category', edit_category_path(category), class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4  border border-blue-500 hover:border-transparent rounded" %>
            <%= link_to 'Delete this category', category, data: { "turbo-method": :delete } , class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4  border border-blue-500 hover:border-transparent rounded" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">New category</h1>

  <%= render "form", product: @category %>

  <%= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class=" border-gray-200 px-4 lg:px-6 py-2.5 dark:bg-gray-800 bg-slate-400">
    <div class="flex flex-wrap items-center justify-between max-w-screen-xl mx-auto">
      <a href="http://127.0.0.1:3000" class="flex items-center">
        <img src="https://w7.pngwing.com/pngs/55/764/png-transparent-daggett-beaver-art-graphy-beaver-animals-photography-social-media.png" class="h-8 mr-3 sm:h-12" alt="Bober Logo" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Bober</span>
      </a>
      <div class="flex items-center lg:order-2">
        <% if current_user %>
          <div data-controller="dropdown" data-dropdown-open-value="false" data-dropdown-opened-class="bg-slate-300">
            <button  data-dropdown-target="activated" data-action="click->dropdown#toggleDropdown">
              <p class="mr-10">Settings</p>
            </button>
            <div data-dropdown-target="dropdownContent" class="fixed ">
              <div class="w-auto overflow-hidden bg-white border rounded-lg shadow">
                <%= link_to 'My orders', orders_path(current_user) , class: 'no-underline block py-3 px-3 text-center text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap' %>
                <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete } , class: 'no-underline block py-3 px-3 text-center  text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap'  %>
                <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'no-underline block py-3 px-5 text-center text-gray-900 bg-white hover:bg-gray-300 whitespace-nowrap'  %>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to 'Log In', new_user_session_path, class:"text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800" %>
          <%= link_to 'Sign Up', new_user_registration_path , class:"text-gray-800 dark:text-white hover:bg-gray-50 focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-4 lg:px-5 py-2 lg:py-2.5 mr-2 dark:hover:bg-gray-700 focus:outline-none dark:focus:ring-gray-800" %>
        <% end %>
      </div>
      <div class="items-center justify-between hidden w-full lg:flex lg:w-auto lg:order-1" id="mobile-menu-2">
        <ul class="flex flex-col mt-4 font-medium lg:flex-row lg:space-x-8 lg:mt-0">
          <li>
            <% if current_user %>
              <%= render 'products/cart_user_session' %>
            <% else %>
              <%= render 'products/cart_session' %>
            <% end %>
          </li>
          <li>
            <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"><%= link_to 'Products', root_path %></a>
          </li>
          <li>
            <a href="#" class="block py-2 pl-3 pr-4 text-gray-700 border-b border-gray-100 hover:bg-gray-50 lg:hover:bg-transparent lg:border-0 lg:hover:text-primary-700 lg:p-0 dark:text-gray-400 lg:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white lg:dark:hover:bg-transparent dark:border-gray-700"><%= link_to 'Categories', categories_path %></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/order_items/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Confirm order</h1>

  <%= render "form", order_item: @order_item%>

  <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/orders/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Confirm order</h1>
  <% if current_user.nil? %>
    <%= render "form_session", order: @order%>
  <% else %>
     <%= render "form_user", order: @order%>
  <% end %>
  <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/_buttons_session.html.erb
 <% if cart.include?(product) %>
  <%= button_to 'Remove', remove_from_cart_path(product), method: :delete, class:"px-2 py-1 font-semibold text-white transition duration-500 bg-red-600 rounded-lg shadow-md text-ms hover:shadow-lg transform-gpu hover:scale-110 "%>
<% else %>
  <%= button_to 'Add to cart', add_to_cart_path(product), method: :post, class:"px-2 py-1 font-semibold text-white transition duration-500 bg-green-400 rounded-lg shadow-md text-md hover:shadow-lg transform-gpu hover:scale-110 "%>
<% end %>

app/views/products/_buttons_user.html.erb
  <% if cart.products.include?(product) %>
    <%= button_to 'Remove', remove_product_path(product), method: :post, class:"px-2 py-1 font-semibold text-white transition duration-500 bg-red-600 rounded-lg shadow-md text-ms hover:shadow-lg transform-gpu hover:scale-110 " %>
  <% else %>
    <%= button_to 'Add to cart', add_product_path(product), method: :post, class:"px-2 py-1 font-semibold text-white transition duration-500 bg-green-400 rounded-lg shadow-md text-md hover:shadow-lg transform-gpu hover:scale-110 " %>
  <% end %>

app/views/products/_cart_session.html.erb
<div data-controller="modal" >
  <button data-action="modal#open" id="open" class='block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent'>
    <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-700 hover:text-gray-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
    </svg>
    <span class="absolute flex ml-4 -mt-6">
      <span class="absolute inline-flex w-3 h-3 bg-pink-400 rounded-full opacity-75 animate-ping"></span>
      <span class="relative inline-flex w-3 h-3 bg-pink-500 rounded-full"></span>
    </span>
  </button>
  <dialog data-modal-target="modal" class="rounded-md">
    <button type="button" data-action="modal#close" class="absolute p-1 text-gray-400 bg-gray-300 rounded-md top-1 right-1 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
      <!-- Heroicon name: outline/x -->
      <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
    <% if @cart.empty? %>
      <table class="w-full mt-4 text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              No items in cart.
            </th>
          </tr>
        </thead>
      </table>
    <% else %>
      <div class="relative overflow-x-auto">
        <table class="w-full mt-4 text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">
                Product name
              </th>
              <th scope="col" class="px-6 py-3">
                Category
              </th>
              <th scope="col" class="px-6 py-3">
                Price
              </th>
            </tr>
          </thead>
          <% @cart.each do |product|  %>
            <tbody>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= product.title %>
                </th>
                <td class="px-6 py-4">
                  <%= product.category.name if product.category %>
                </td>
                <td class="px-6 py-4">
                  <%= number_to_currency(product.price, unit: "UAH", delimiter: " ", format: "%n %u") %>
                </td>
              </tr>
            </tbody>
          <% end %>
          <tbody>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                Total
              </th>
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
              </th>
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                <%= number_to_currency(total_price_session, unit: "UAH", delimiter: " ", format: "%n %u") %>
              </th>
            </tr>
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
              <%= link_to 'To order', new_order_path, class: "bg-transparent hover:bg-blue-900 text-blue-700 font-semibold hover:text-white py-2 px-4  border border-blue-500 hover:border-transparent rounded"%>
            </th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <th>
            </th>
            <th>
              <%= link_to 'Empty cart', delete_session_cart_path, class: "bg-transparent hover:bg-red-900 text-blue-700 font-semibold hover:text-white py-2 px-4  border border-blue-500 hover:border-transparent rounded" %>
            </th>
          </tbody>
        </table>
      </div>
    <% end %>
  </dialog>
</div>

app/views/products/_cart_user_session.html.erb
<div data-controller="modal">
  <button data-action="modal#open" id="open" class='block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent'>
    <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-700 hover:text-gray-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
    </svg>
    <span class="absolute flex ml-4 -mt-6">
      <span class="absolute inline-flex w-3 h-3 bg-pink-400 rounded-full opacity-75 animate-ping"></span>
      <span class="relative inline-flex w-3 h-3 bg-pink-500 rounded-full"></span>
    </span>
  </button>
  <dialog data-modal-target="modal">
    <button type="button" data-action="modal#close" class="absolute p-1 text-gray-400 bg-gray-300 rounded-md top-1 right-1 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">      <!-- Heroicon name: outline/x -->
      <svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    </button>
    <% if @cart.products.empty? %>
      <div class="relative overflow-x-auto">
        <table class="w-full mt-4 text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">
                No items in cart.
              </th>
            </tr>
          </thead>
        </table>
      </div>
    <% else %>
      <div class="relative overflow-x-auto">
        <table class="w-full mt-4 text-sm text-left text-gray-500 dark:text-gray-400">
          <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
              <th scope="col" class="px-6 py-3">
                Product name
              </th>
              <th scope="col" class="px-6 py-3">
                Category
              </th>
              <th scope="col" class="px-6 py-3">
                Price
              </th>
            </tr>
          </thead>
          <% @cart.products.each do |product|  %>
            <tbody>
              <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                  <%= product.title %>
                </th>
                <td class="px-6 py-4">
                  <%= product.category.name if product.category %>
                </td>
                <td class="px-6 py-4">
                  <%= number_to_currency(product.price, unit: "UAH", delimiter: " ", format: "%n %u") %>
                </td>
              </tr>
            </tbody>
          <% end %>
          <tbody>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                Total
              </th>
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
              </th>
              <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                <%= number_to_currency(total_price_current_user, unit: "UAH", delimiter: " ", format: "%n %u") %>
              </th>
            </tr>
            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
              <%= link_to 'To order', new_order_path, class: "bg-transparent hover:bg-blue-900 text-blue-700 font-semibold hover:text-white py-2 px-4  border border-blue-500 hover:border-transparent rounded"%>
            </th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <th>
            </th>
            <th>
              <%= link_to 'Empty cart', empty_cart_path, class: "bg-transparent hover:bg-red-900 text-blue-700 font-semibold hover:text-white py-2 px-4  border border-blue-500 hover:border-transparent rounded" %>
            </th>
          </tbody>
        </table>
      </div>
    <% end %>
  </dialog>
</div>

app/views/products/edit.html.erb
<div class="w-full mx-auto mb-4 md:w-2/3">
  <h1 class="text-4xl font-bold">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", @product, class: "ml-2 rounded-lg py-3 px-5 bg-white inline-block font-medium" %>
  <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-white inline-block font-medium" %>
</div>

app/views/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", product: @product %>

  <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/products/show.html.erb
<div class="flex w-full mx-auto md:w-2/3">
  <div class="mx-auto mb-4">
    <% if notice.present? %>
      <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
    <% end %>

    <%= render @product %>

    <%= link_to 'Edit this product', edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this product', product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 font-medium" if current_user %>
      <%= button_to 'Destroy this product', destroy_for_session_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 font-medium" if current_user.nil? %>
    </div>
    <%= link_to 'Back to products', products_path, class: "ml-2 rounded-lg py-3 px-5 bg-white inline-block font-medium" %>
  </div>
</div>